DROP TABLE    voting     IF EXISTS;
DROP TABLE    dishs      IF EXISTS;
DROP TABLE    user_roles IF EXISTS;
DROP TABLE    restaurant IF EXISTS;
DROP TABLE    users      IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ  AS INTEGER START WITH 100000;

CREATE TABLE users
(
  id         INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name       VARCHAR(255)            NOT NULL,
  email      VARCHAR(255)            NOT NULL,
  password   VARCHAR(255)            NOT NULL,
  registered TIMESTAMP DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON USERS (email);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE restaurant
(
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);


CREATE TABLE voting
(
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  user_id       INTEGER   NOT NULL,
  restaurant_id INTEGER   NOT NULL,
  date_time     TIMESTAMP NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)  ON DELETE CASCADE
);
CREATE TABLE dishs
(
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name          varchar(355) NOT NULL,
  restaurant_id INTEGER      NOT NULL,
  date          TIMESTAMP DEFAULT now()   NOT NULL,
  price         INTEGER   NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE

); CREATE UNIQUE INDEX dishs_unique_name_idx ON DISHS (name,restaurant_id);