DROP TABLE dishs IF EXISTS;
DROP TABLE menus IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE restaurant IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ
  AS INTEGER
  START WITH 100000;




CREATE TABLE restaurant
(
   id    INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
   name             VARCHAR(255)            NOT NULL

);

CREATE TABLE menus
(
    id                  INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    restaurant_id       INTEGER               NOT NULL,
    voting              INT,
  datetime              TIMESTAMP DEFAULT now() NOT NULL,
  CONSTRAINT restaurant_menus_idx UNIQUE (restaurant_id, datetime),
  FOREIGN KEY (restaurant_id) REFERENCES RESTAURANT (id) ON DELETE CASCADE

);
CREATE TABLE dishs
(
menu_id              INTEGER                 NOT NULL,
name                 VARCHAR(255)            NOT NULL,
price                INT,
CONSTRAINT menus_dishs_idx UNIQUE (menu_id, name),
  FOREIGN KEY (menu_id) REFERENCES MENUS (id) ON DELETE CASCADE
);
CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  isvoting_to_dey  BOOLEAN DEFAULT FALSE   NOT NULL
);